### ISSUE TITLE
HEC-DSS files load slowly

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#10]
HEC-DSS files load using the command line DSSUTIL.exe. A more tightly integrated method would likely be faster.

**Comment by tjrocha** [comment]
A DSSUTIL C library is scheduled for public release in Feb 2017 by USACE-HEC. Could probably look into using this code with something like what is mentioned in the link below.

http://stackoverflow.com/questions/9093292/use-a-c-library-from-c-sharp-code

**Comment by ktarbet** [comment]
Nice.  We could do something similar what was once done with a model called MODSIM.  It was in c/c++ code, we created a c++(.net) layer to use the c code. https://en.wikipedia.org/wiki/C%2B%2B/CLI
