### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#105]
Running Pisces 2.0.42  on windows 7, with updated .net.  This windows computer in question does not have a typical Documents Directory.  A link to 'My Documents' gives a permission denied message.

![image](https://cloud.githubusercontent.com/assets/4818531/21532824/7362bf26-cd11-11e6-8d69-480673610e3b.png)

We need better error message to debug this, Or preferably a safe fallback of we can't open the database.

**Comment by ktarbet** [comment]
One test will be running from command line specifying database file to open like this:

![image](https://cloud.githubusercontent.com/assets/4818531/21532921/9772ba6e-cd12-11e6-893e-9b939b009b38.png)

**Comment by tjrocha** [comment]
We could use C:\Temp or the environment variable %temp%. The environment variable should exist since other windows systems rely on it.

**Comment by ktarbet** [comment]
More info.

![image](https://cloud.githubusercontent.com/assets/4818531/21533701/bab07cac-cd1a-11e6-8d6f-47ea09977627.png)

**Comment by ktarbet** [comment]
I solved this specific issue by specifying path/filename in a Pisces shortcut.
![image](https://cloud.githubusercontent.com/assets/4818531/21553942/cf23ef08-cdc8-11e6-89de-4f7095406c30.png)

How about we set the default path (when there is no history of what file to open) to be path to pisces.exe?

```csharp
fileName = Path.Combine(FileUtility.GetExecutableDirectory(), "tsdatabase.pdb");
```
