### ISSUE TITLE
Pisces Login - move away from the  key files 

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#106]
The user should enter the password instead of having a text file.  We have the basic functionality (with persistence via encrypted password) but we need to remove the code that uses the files such as postgres_key.txt and mysql_key.txt.  

![image](https://cloud.githubusercontent.com/assets/4818531/21536016/532a9f02-cd3a-11e6-8705-fafa14c87a87.png)

**Comment by tjrocha** [comment]
Agree. Looking at the code though, how would we handle RWIS Sync which currently uses a mysql_key.txt file? Should I put the password in as an AppSetting so we can run it in command line?

https://github.com/usbr/Pisces/blob/master/Rwis.Sync/App.config

**Comment by tjrocha** [comment]
Ok, I'll work on eliminating the text file dependency. FYI, I get the error below when I try to connect to the RWIS DB from compiled source. Are there still issues with the .Net upgrade?

![picture1](https://cloud.githubusercontent.com/assets/8174126/21548195/bfd4797e-cd9f-11e6-92c3-c840ee96c808.png)
