### ISSUE TITLE
sitecatalog latitude and longitude and elevation should be double in the database

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#107]

**Comment by ktarbet** [comment]
We will also need to update the SQL commands that create the database tables.  [CreateSQL](https://github.com/usbr/Pisces/blob/master/TimeSeries/TimeSeriesDatabase.CreateSQL.cs) Additionally existing databases will need conversion to double.  That might require lat/long values to allow DBNull

**Comment by ktarbet** [comment]
We will also need to verify functionality of [web service](https://github.com/usbr/Pisces/blob/master/PiscesWebServices/JSONSites.cs) features that use the lat/long to generate [GeoJson](http://geojson.org/)

**Comment by blounsbury** [comment]
I assume this means we need to increment the FileVersion in CreatePiscesInfoTable() to detect existing databases that need conversion? I've written some code for the conversion with that assumption, if that's correct I can commit some changes. I don't know how to verify the web service features.

**Comment by ktarbet** [comment]
great!  Yes that approach should work.  There are only two databases in production that I know of (one mysql and one postgres)  if necessary we can do a manual process with a sql script.  We can test the web service manually and fix as needed.

**Comment by blounsbury** [comment]
Edits committed. However, I haven't tested anything :-).

**Comment by ktarbet** [comment]
We can test using a backup on a test server for postgresql.  We might need to use sql "alter table" instead of dropping the table depending on references in the database.  @tjrocha  do you know if there are triggers or references in your mysql version that would prevent this from working?

**Comment by tjrocha** [comment]
The only TRIGGERS that I have work with the SERIESCATALOG. I do have some DB VIEWS that use the SITECATALOG although this shouldn't prevent anyone from dropping it.

**Comment by ktarbet** [comment]
Someone else did the testing for us -- sitecatalog references proprieties -- In my database that means we can't drop the table.

![image](https://cloud.githubusercontent.com/assets/4818531/21724204/b10e95ee-d3f0-11e6-87fa-035ec923693a.png)

**Comment by ktarbet** [comment]
I've fixed this in 642bb7a

**Comment by ktarbet** [comment]
We need to move schema changes into v3 branch since the schema change can break existing code/apps.

**Comment by ktarbet** [comment]
In postgresql here are some commands to alter the column from character to float.  
Something like latitude='' will first need to be assigned a number before running these SQL commands.

alter table sitecatalog alter column latitude DROP DEFAULT;
alter table sitecatalog alter column latitude type  float USING latitude::float;

alter table sitecatalog alter column longitude DROP DEFAULT;
alter table sitecatalog alter column longitude  type  float USING longitude::float;
