### ISSUE TITLE
An open source Spreadsheet component is needed. 

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#11]
http://exceldatareader.codeplex.com/ is being used in Core/ExcelUtility.  ExcelUtility loads a whole sheet into memory as a DataTable. 

However for Pisces Excel imports using @tonyqus  https://github.com/tonyqus/npoi is needed to replace a third party component that is doing a high performance read with lots of error checking to throw out invalid time series data.  The code that needs to be replaced is in the assembly Reclamation.TimeSeries.Excel.dll.   The code is in https://github.com/usbr/Pisces/tree/master/TimeSeries.Excel

**Comment by ktarbet** [comment]
.\Core\NpoiExcel.cs is slowly developing

**Comment by tonyqus** [comment]
I didn't catch you. What's the topic of this thread?

2015-07-10 3:45 GMT+08:00 Karl Tarbet <notifications@github.com>:

**Comment by ktarbet** [comment]
We are reading timeseries data using NPOI. 
We need a high performance way to read Excel columns  (DateTime,double,[string])  into a DataTable.  So far NPOI is working great.  We are working on long term replacing these two classes using NPOI:

https://github.com/usbr/Pisces/blob/master/TimeSeries.Excel/SpreadsheetGearExcel.cs
https://github.com/usbr/Pisces/blob/master/TimeSeries.Excel/SpreadsheetGearSeries.cs


https://github.com/usbr/Pisces/blob/master/Core/NpoiExcel.cs
is our draft replacement for SpreadsheetGearExcel.cs

Thanks @tonyqus for your work on NPOI!

**Comment by tonyqus** [comment]
You should try Toxy. ToxySpreadsheet is what you want. It can be downloaded
from toxy.codeplex.com.

2015-07-10 22:39 GMT+08:00 Karl Tarbet <notifications@github.com>:
