### ISSUE TITLE
State of Idaho web-service URL change

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#112]
https://idwr.idaho.gov/files/help/Accounting-Time-Series-Users-Manual.pdf

In summary,  the url in IDWRDailySeries.cs need to be changed to:

https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/History?sitelist=13050018&
yearlist=2015,2014,2013,2012,2011&yeartype=IY

Perhaps some other changes will be needed.

This URL is used to import 'published' data from the state -- typically daily canal flows.

**Comment by tjrocha** [comment]
This change is included in the new Import IDWR Series functionality in 6e314d0db36ac013c7674c7b237553803b980b66. The new Series constructor now requires a station number and Hydromet-style parameter code. 

`var s = new IDWR.IDWRDailySeries(station, parameter);`
`s.Read(t1, t2);`

**Comment by ktarbet** [comment]
should have been step toward #121
