### ISSUE TITLE
USGS Rating table (with no BREAKPOINT)  causes error.

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#114]

**Comment by tjrocha** [comment]
Feel free to close if fix is confirmed on your end.

![image](https://cloud.githubusercontent.com/assets/8174126/23964253/275a3d24-0971-11e7-92ad-e5eb5957db5f.png)

**Comment by ktarbet** [comment]
Thanks @tjrocha  That fix works for me also!
