### ISSUE TITLE
TimeSeriesImporter does not handle second (or greater) level of dependent calculations

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#115]
Given:
aga_fb = (raw data)
aga_af = FileRatingTable(aga_fb,"aga_af.csv")
aga_qr = FileRatingTable(aga_gh,"aga_qr.csv")
aga_qs = FileRatingTable(aga_fb,"aga_qs.csv")

aga_q = aga_qs + aga_qr

------------

Expect that aga_q will be computed during import. (This is not working) . However, it does work for daily dependent type calculations.

**Comment by tjrocha** [comment]
Would it be feasible to recursively feed each output into the dependency resolver? So in this example, the input aga_fb results in output {aga_af, aga_qr, aga_qs}. Can we loop through the outputs to append more required calculations so input {aga_af, aga_qr, aga_qs} would result in output {aga_q, ... }?

Would there be a chance that we get into an infinite loop by performing recursion in this way?

**Comment by ktarbet** [comment]
Yes, I agree that is what we need to do.   In fact we do this with the daily and might be able to generalize that for both daily and instant.   I have some code that prevents infinite loop in both TimeSeriesImporter.cs and TimeSeriesDependency.cs
