### ISSUE TITLE
Pisces context menu for adding series has too much stuff

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#128]
Could we break out modeling data in a separate sub-menu?
What other ways are there to organize this?

**Comment by tjrocha** [comment]
Good point. Should we split it up by data source type? I mean Local Files (Excel, Access, RDF, etc) and Web Services (USGS, IDWR, OWRD, etc). This way we can add a check to see of there is an internet connection and hide the import options that rely on web services.

**Comment by ktarbet** [comment]
Data source may work.  I would also like to compartmentalize (put at the bottom, or under a label 'more..'.)  'rarely used' items, such as Rio Grande spreadsheet, URGSIM,etc..

**Comment by tjrocha** [comment]
Ok. Let me put something together in a branch.

**Comment by tjrocha** [comment]
Screenshots of results based on discussion in this thread. Would this work @ktarbet?

![image](https://cloud.githubusercontent.com/assets/8174126/26327422/429d683c-3ef4-11e7-9070-46bbfa3f5705.png)

![image](https://cloud.githubusercontent.com/assets/8174126/26327427/45161366-3ef4-11e7-8272-c7031801b835.png)

![image](https://cloud.githubusercontent.com/assets/8174126/26327430/47a253f6-3ef4-11e7-9e25-c4988be282a9.png)

**Comment by ktarbet** [comment]
Good improvement!     how about calling this  "From File"  or "From web".    
"Add Hec dss  File " can be under  "From file"   and  "US ... data query" is from web.
What does @blounsbury  Think?

**Comment by ktarbet** [comment]
OK.   I have thought about dropping the Plug-in-code.  This is another argument to drop plugins.
