### ISSUE TITLE
Analysis feature request - in Summary Hydrograph Allow plotting multiple years

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#141]
![image](https://user-images.githubusercontent.com/4818531/30602258-4d184756-9d21-11e7-8907-81156497542a.png)

**Comment by tjrocha** [comment]
want me to take a stab at it today?

**Comment by ktarbet** [comment]
Sounds great!   Thanks.

**Comment by ktarbet** [comment]
Looks nice!   Thanks -- you are fast.
