### ISSUE TITLE
Analysis Feature Request - Allow customizing the exceedance levels

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#142]
This could be stored in the pisces_info table.

The specific request is to include 25% and 75% in the Summary Hydrograph Analysis feature.

![image](https://user-images.githubusercontent.com/4818531/30602485-e7e4207a-9d21-11e7-8d8e-6fbb2d1ec0de.png)

**Comment by ktarbet** [comment]
Perhaps we just just add 25% and 75%

**Comment by tjrocha** [comment]
that or we add a text box where a user can add custom levels separated by a delimiter.

Ex: *25,50,75* or *0,50,100*

**Comment by ktarbet** [comment]
I like the text box idea

**Comment by blounsbury** [comment]
Sounds fine to me, as long as the existing structure stays. I would also think there is enough empty windows form space to have 5% increments. Not sure if 0% and 100% exceedance levels make much sense or would be useful.

**Comment by tjrocha** [comment]
ok, i did pretty much this for #143. i'll go ahead and do the same thing for this one.

**Comment by ktarbet** [comment]
@tjrocha   Thanks again!
