### ISSUE TITLE
Visualization Improvement: Embedded Browser as a Visualization Output Window

### ISSUE THREAD

**Issue by tjrocha** [usbr/Pisces#148]
Add an embedded browser as another tab in Pisces and build JS libraries to work with Reclamation.TimeSeries.Series() objects for use in visualization outputs. This would allow us to leverage the many cool and interesting ways to visualize data using web-based JS visualization libraries such as [D3](https://d3js.org/), [DyGraphs](http://dygraphs.com/), [Leaflet](http://leafletjs.com/), etc.

**Comment by ktarbet** [comment]
This is related to https://github.com/usbr/Pisces/issues/140

**Comment by ktarbet** [comment]
closing this issue.  What we want is a web application served from a server, instead of embedding web app inside a desktop application.
