### ISSUE TITLE
reading riverware rdf scenarios fails with rdf's of the same name

### ISSUE THREAD

**Issue by blounsbury-usbr** [usbr/Pisces#161]
Loaded multiple rdf's from different folders but with the same filename into Pisces and Pisces plotted only the first scenario in the list.

**Comment by ktarbet** [comment]
I having an error with multiple runs (MRM) where there are multiple 'scenarios' in the same file.  
The file name determined in RiverWareSereis.CreateScenario() is not valid.

To reproduce.   
1) create empty pisces database
2) import the attached file
3) open tree and select an object.

[traces.txt](https://github.com/usbr/Pisces/files/1964026/traces.txt)

**Comment by ktarbet** [comment]
For MRM the scenario selector Path looks like:

| Name | Checked | Path |
| ------------- | ------------- |--|
|1928 | x | ScenarioNumber=1|
|1929 | x | ScenarioNumber=2|

-- Another way to use scenarios is a separate RDF file for each scenario:

| Name | Checked | Path |
| ------------- | ------------- |--|
|Output| x | FileName=ScenarioRuns\MIROC5_RCP85_MACA_VIC_P1\Output.rdf|
|Output | x | FileName=ScenarioRuns\MIROC5_RCP85_MACA_VIC_P3\Output.rdf|


The method CreateScenario() needs some refactoring, perhaps a function that finds the proper filename.
