### ISSUE TITLE
Summary statistics on selected Table values

### ISSUE THREAD

**Issue by blounsbury** [usbr/Pisces#22]
Would be nice to have a right-click option "Statistics" in the Table view. I wanted to see what the sum of a few values was. Something like this:

![image](https://cloud.githubusercontent.com/assets/1508213/6720397/2ca74168-cd88-11e4-8a9b-4a0b16981ae5.png)

**Comment by ktarbet** [comment]
How about using the method in DataGridSelection ComputeSelectedStats()?  It  has min,max,avg,sum,count.
https://github.com/usbr/Pisces/blob/master/Core/DataGridSelection.cs

That is used by Hdb-Poet to do something like the excel status bar. This image below is from HydrometTools that has a similar feature.
![image](https://cloud.githubusercontent.com/assets/4818531/6721318/a37b3430-cd91-11e4-9849-d55ef095e183.png)

**Comment by blounsbury** [comment]
Nice. I like that idea. I could probably look into it over the weekend.
