### ISSUE TITLE
Teacup needs work to be cross platform

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#252]
The Teacup program https://github.com/usbr/Pisces/tree/master/Applications/teacup reads a base gif files and adds text and 'Teacups' that represent current conditions.

To run the Teacup on Linux could be done in two steps.

1. Use System.Drawing.Common (link below) to allow quicker migration to .net 6.0 
2. Migrate to another cross platform graphics library

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action

**Comment by blounsbury-usbr** [comment]
Just wanted to note here that System.Drawing.Common will be unavailable in .net 7.0. So, I'd vote to spend time migrating to another cross platform graphics library.
