### ISSUE TITLE
YAKHYD to PNHYD Migration - Teacup Fix

### ISSUE THREAD

**Issue by tjrocha** [usbr/Pisces#258]
https://github.com/usbr/Pisces/blob/556caab22f0ce3d250c8b15de2d6c3c608be2a0f/Applications/teacup/Program.cs#L33

We can remove this check in future iterations of the code. Currently tries to hit YAKHYD if the argument has 'yak' in the filename. YAKHYD no longer exists so fine to make the code hit PNHYD for all queries.

**Comment by blounsbury-usbr** [comment]
Ok. Maybe we should check if pnhyd is available, if not, try yakimalinux. This also seems like a good time to clear out the other hydromethost options: PN and Yakima.

**Comment by blounsbury-usbr** [comment]
closed by #259
