### ISSUE TITLE
Calculation series fails if dependent series name changed

### ISSUE THREAD

**Issue by blounsbury** [usbr/Pisces#26]
I added a hydromet series "amf af" saying "using simple name" then created the calculation series "AMF_AF_Monthly". It worked, but then I renamed "amf af" to "AMF_AF_Daily" and went to update the calculation series and get this:

![image](https://cloud.githubusercontent.com/assets/1508213/7752219/84df6104-ff9b-11e4-9a39-f6d6055b2a2d.png)

**Comment by ktarbet** [comment]
I'm having trouble reproducing this. I tried two simple test. Can you please provide steps to reproduce?  Is it possible there is another series with the same name?

**Comment by blounsbury** [comment]
Should have realized that, yes, there is another series with the same name.
There is no issue. Thanks.

**Comment by ktarbet** [comment]
Looks like we need a better error message "duplicate names"

**Comment by blounsbury** [comment]
Yes, great idea.
