### ISSUE TITLE
Calculation series fails if dependent series nested in folders

### ISSUE THREAD

**Issue by blounsbury** [usbr/Pisces#27]
I created a hydromet series "amf af" two folders deep, renamed it to "AMF_AF_Daily". Then tried to create a calculation series, but get this:

![image](https://cloud.githubusercontent.com/assets/1508213/7752408/80ffb272-ff9c-11e4-8f3e-436ee7deb8b8.png)

**Comment by blounsbury** [comment]
Strange, doesn't matter if the series is nested in folders, ref #26. I thought this worked previously.

![image](https://cloud.githubusercontent.com/assets/1508213/7752655/ea30b07e-ff9d-11e4-946f-2393ae1c0d85.png)

**Comment by ktarbet** [comment]
How did you resolve this?  Restart Pisces?

**Comment by blounsbury** [comment]
I thought this was a separate issue, but the same behavior as in #26 is
seen within nested folders. So just one issue.
