### ISSUE TITLE
Add Pisces series

### ISSUE THREAD

**Issue by blounsbury** [usbr/Pisces#28]
Would be nice to have Data->Add Pisces Series. Bring in a Pisces Series from another database.

**Comment by ktarbet** [comment]
The user interface design for this may be the key.  Perhaps something like the equation editor interface that allows selecting series.  V2.0.2 allows importing an entire Database, right click Add.

**Comment by ktarbet** [comment]
You can Add a SQLite Pisces database with right click in the tree view -- Add Pisces Database file.   The destination database can be a sever.  But you are limited to importing from SQLite format.

![add_database](https://cloud.githubusercontent.com/assets/4818531/8260014/3df7651c-167e-11e5-8f4b-3639232e8dff.png)

**Comment by blounsbury** [comment]
​This menu and the Data menu are out of sync :)​
