### ISSUE TITLE
Pisces should remember what servers it has connected to.

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#43]
At a minimum the list of servers should be editable somewhere like the config file.
This is in the menu File->Connect to server 

![server_selection](https://cloud.githubusercontent.com/assets/4818531/12658235/10bc3a54-c5c5-11e5-8b96-9969d17875f1.png)

Even better is a growing history of servers used.

**Comment by ktarbet** [comment]
@blounsbury do you have some code/experience that may help with this.

**Comment by blounsbury** [comment]
I just did something similar in MODSIM with recent files instead of using the windows registry I used the .net application settings. I would add a StringCollection application setting to store and keep track of the items. I think it's nice to have a way to clear the items too.

**Comment by ktarbet** [comment]
I've done something very simple -- saves any changes.  We still need a way to clear.
