### ISSUE TITLE
Scenario Sorting Issue: April 22 2016 USBR Email

### ISSUE THREAD

**Issue by tjrocha** [usbr/Pisces#54]
@blounsbury submitted issue follows:

Still getting the SQL error. Another beta tweak needed. In the scenario selector, 'sort/using', the list should be unique I assume. A HashSet should automatically handle that.

![image](https://cloud.githubusercontent.com/assets/8174126/14763650/6bc8bfd4-0950-11e6-8c87-700c67ccb14d.png)

**Comment by ktarbet** [comment]
should this issue be closed?   I think there might be a separate issue of naming convention in Pisces for MODSIM data.

**Comment by tjrocha** [comment]
Yes. I'll close it here shortly.
