### ISSUE TITLE
Import Campbell Scientific LoggerNet (TOACI1, and TOA5)

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#55]
The goal is to import LoggerNet files with a right-click in Pisces.   Currently if you delete the 'extra' header lines and pretend this is an excel file it works.  However, when loggernet reconnects the header gets restored.  

I suggest a simple addition   Add-> LoggerNet ... Similar to the Add->CR10X feature.

Should we skip the RECNBR -- record number?
Is TMSTAMP -- (time stamp) always spelled this way?

TOACI1 -- short header (drop first line)
TOA5 - - longer header  (drop first two lines)

Here is an example TOAC1 format.
[Site 56_Hourly.txt](https://github.com/usbr/Pisces/files/235071/Site.56_Hourly.txt)

**Comment by AgriMet** [comment]
The record number can be skipped. I believe TMSTMP is always spelled that way, as LoggerNet adds it.

**Comment by ktarbet** [comment]
Here is [Code](https://github.com/usbr/Pisces/blob/master/TimeSeries/DataLogger/LoggerNetFile.cs) that reads loggernet files.  This will be straight forward.
