### ISSUE TITLE
Develop rating tables feature request

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#60]
Allow development of rating table by adding measurement points and selecting which points are used to develop the curve.  

key features:
- Store measurements
- Save selected measurements
- Save equation type and associated data  (Logarithmic interpolation, polynomial )
- Generate tabular table with stage varying a 0.01 feet increments.

![rating_curve_usgs](https://cloud.githubusercontent.com/assets/4818531/15657707/973ef18c-2670-11e6-97a6-a045090e8332.jpg)

Image above is from the USGS:
 [USGS Discharge Ratings at Gauging Stations ](http://pubs.usgs.gov/twri/twri3-a10/pdf/TWRI_3-A10.pdf)

A good starting point is the Hydrography Application -- It imports different types of flow measurements and is used to develop rating tables.  It uses polynomial equations which might not be helpful  in natural channels so Logarithmic equations will need to be added.   

I've put a few screen shots of the Hydrography application in the wiki:
[Rating Table development](https://github.com/usbr/Pisces/wiki/rating-tables)

**Comment by tjrocha** [comment]
added some initial code to perform linear regression in b54a92967e5dd97b8273c28e21963ac0587457d9. Could further expand using the other Math.Net Numerics regression functions.

**Comment by tjrocha** [comment]
Added capability to generate log scale regression lines via 16db9efe9d374784b023ba70fcd915dba99ca871. also switched axes back per @ktarbet.

![picture1](https://cloud.githubusercontent.com/assets/8174126/17375832/960d6c74-5967-11e6-9092-ae0ae1a8612f.png)

**Comment by tjrocha** [comment]
Added capability to perform multi-part piecewise linear regressions using user defined breakpoints in 203d7f91d058ff0283077536d82187b9af55b4c5. Combined with the log-scale regression function, we should now be able to fully replicate the image shown in @ktarbet 's 1st post of this thread.

![picture1](https://cloud.githubusercontent.com/assets/8174126/17388800/61bc3274-59b3-11e6-9793-85df4cb25138.png)

**Comment by ktarbet** [comment]
I'm planning to move "developing rating tables" type features in a separate simple app.  Another day we might pull this back into Pisces.
