### ISSUE TITLE
Calculation Series properties is ugly unless you make it larger

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#62]
To reproduce in Pisces UI add calculation series.

![bug1](https://cloud.githubusercontent.com/assets/4818531/15715764/ed94a3e8-27dc-11e6-966a-8dd662b8912f.png)

**Comment by tjrocha** [comment]
Could probably make it a drop down box whose size is adjusted by the length/size of the contents. See code below from Reclamation.TimeSeries.Forms > ScenarioSelector.cs

`
private void AdjustWidthComboBox_DropDown(object sender, System.EventArgs e)
        {
            ComboBox senderComboBox = (ComboBox)sender;
            int width = senderComboBox.DropDownWidth;
            Graphics g = senderComboBox.CreateGraphics();
            Font font = senderComboBox.Font;
            int vertScrollBarWidth =
                (senderComboBox.Items.Count > senderComboBox.MaxDropDownItems)
                ? SystemInformation.VerticalScrollBarWidth : 0;

            int newWidth;
            foreach (string s in ((ComboBox)sender).Items)
            {
                newWidth = (int)g.MeasureString(s, font).Width
                    + vertScrollBarWidth;
                if (width < newWidth)
                {
                    width = newWidth;
                }
            }
            senderComboBox.DropDownWidth = width;
        }
`

**Comment by ktarbet** [comment]
A drop down box would save lots of space if that is used for the equation list instead of list box. Another option is a right click in the equation area.  Right click and show list of equations.   I think intellisense (like in Visual Studio) may be too much to ask for :)

**Comment by tjrocha** [comment]
I can look into the IntelliSense option to see if/how we can do it. Otherwise, doing a dropdown would be very straightforward. Would you like me to do this?

**Comment by blounsbury** [comment]
Pisces 2.0.20.0, calculation properties is not so ugly on my machine. Seems like the minimum form sizes are not behaving on @ktarbet machine. The benefit of the list is drag and drop of equations, with a drop down you could have an Insert or Add equation button but now I have to click twice to get the equation in there. Also, clicking on a function currently quickly shows some help. I would vote to get the minimum form sizes working properly so it's not "ugly".

![image](https://cloud.githubusercontent.com/assets/1508213/15716864/9613d382-27e1-11e6-8178-b15fe3d342de.png)

**Comment by tjrocha** [comment]
I see what you mean. I thought the layout was changed hence causing it to be 'ugly'... It shows up ok on my machine as well. Disregard my suggestion...

**Comment by ktarbet** [comment]
@blounsbury  also mentioned a DPI scaling mode as a possible solution.
