### ISSUE TITLE
Revise?   MissingValueFlag = -999.0 

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#66]
We may need a [Point.MissingValueFlag](https://github.com/usbr/Pisces/blob/master/TimeSeries/Point.cs) that is less likely to happen?   A multi step calculation (see below) computed an intermediate value of exactly  -999.0.   This resulted in a false positive for missing data.

daily_luc_qu = (and_af-and_af[t-1]+ark_af-ark_af[t-1]+luc_af-luc_af[t-1])/1.98347+luc_qd

**Comment by tjrocha** [comment]
Maybe we can use double.NaN if plotting missing values is not important. 

That or use [-1 * Math.Pi] or double.MinValue? Choice depends on how noticeable we want the missing value to be in the plotting window; the former might not show up as clearly on the plot axes while the latter will definitely dwarf everything in comparison...

**Comment by ktarbet** [comment]
Null might be good, but the code doesn't support that at this time.  
Also we need to consider some databases have different abilities on min,max values.
