### ISSUE TITLE
visualize water temperature varying with time and depth

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#68]
Goal:  display water temperature data that comes from water temperature sensors suspended at different levels in a large reservoir or lake.  Data is collected at an hourly interval.

This reminds me of a @tjrocha  Pisces branch that uses HTML to visualize.  For a short term goal a command line utility (or menu) to generate static html would be a good start.

# Examples:

from:  http://greatlakesbuoys.org/images/output/tn-3.png
![tn-3](https://cloud.githubusercontent.com/assets/4818531/16123331/ce547202-33a7-11e6-8ab0-e07f8e7390c5.png)

from: http://www.nwd-wc.usace.army.mil/ftppub/water_quality/tempstrings/DWR_S1_2016_05.html
![usace_tempprofile](https://cloud.githubusercontent.com/assets/4818531/16123485/63d06e08-33a8-11e6-838c-e416887241dc.png)

From @tjrocha 
![gcl1-animated](https://cloud.githubusercontent.com/assets/4818531/16125879/e48fc098-33b2-11e6-9634-cbddbb91e813.gif)

**Comment by ktarbet** [comment]
I have an initial design (image below) that optionally includes the water surface elevation (blue line).  To animate in time we can try to use a tool called bumpkit by @DataDink  .  
![pisces_profile_tool](https://cloud.githubusercontent.com/assets/4818531/16311919/ad1af966-392f-11e6-96b5-906403e6ecb0.png)

**Comment by ktarbet** [comment]
sample output. 
![2005-gcl-profile](https://cloud.githubusercontent.com/assets/4818531/16317611/29160fc4-3949-11e6-989b-fd8029f2db93.gif)

**Comment by blounsbury** [comment]
Cool stuff @ktarbet!
