### ISSUE TITLE
Feature needed:  Water year report.

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#72]
This has multiple uses including webservice.

[PiscesWebServices](/usbr/Pisces/tree/master/PiscesWebServices)

There is some code in [Reports] (/usbr/Pisces/tree/master/TimeSeries/Reports.cs)  -- But that is for monthly.

The Image below is what we need:

![wy_report](https://cloud.githubusercontent.com/assets/4818531/16459468/1b6a6d02-3de0-11e6-987c-17f94e7c8cc4.png)

**Comment by robertherrera** [comment]
I am working issues with making multiple years print consecutively.
