### ISSUE TITLE
Import USGS Data end date ignored

### ISSUE THREAD

**Issue by blounsbury** [usbr/Pisces#75]
Add a USGS series and change the end date range to import. Data up to yesterday is imported instead of the entered end date. End date is ignored.

**Comment by ktarbet** [comment]
Thanks for reporting this issue.  Will you please post a screen shot that could be use to reproduce.
Is this a daily streamflow data import?

**Comment by blounsbury** [comment]
Sure. Note end date is set to 6/28/2016:

![image](https://cloud.githubusercontent.com/assets/1508213/16593313/f62d9246-42a1-11e6-9ec0-08a3cfdada8c.png)

And result in Table:

![image](https://cloud.githubusercontent.com/assets/1508213/16593344/0fa9b2cc-42a2-11e6-9bc1-6999cd1ebb94.png)
