### ISSUE TITLE
USGS has changed their webservice  

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#80]
Pisces.NunitTests.SeriesTypes.TestUsgs.TestDaily is failing.  

http://help.waterdata.usgs.gov/news/061016

Data descriptors (DDs) are replaced with time-series identifiers (TSIDs).

**Comment by tjrocha** [comment]
Commit 43933bb463283219993bfa11f9236c929a192d3d fixed one of the test failures for USGS real time. I will propagate these changes to UsgsDailiyValueSeries.cs to fix the remainder of the errors.

**Comment by tjrocha** [comment]
Fully fixed with c3a8a986bcaf9929119baf51df8493ae26c43e2b.

Propose changing the scheme of using RDB with hardcoded row-substring integer positions with using the WaterML2.0 service and using built-in C# functions to convert xml to Data Table.

**Comment by ktarbet** [comment]
thanks @tjrocha !   I'll mark this closed.   I'm ok if we switch to waterML2.0.
