### ISSUE TITLE
USGS will be switching to https only Dec 31, 2016  Updates needed

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#86]
The staging server can be used for testing. see examples below

water data
**http**
http://waterdata.usgs.gov/nwis/uv?format=html&period=7&site_no=13206000

**https**
https://staging.waterdata.usgs.gov/nwis/uv?format=html&period=7&site_no=13206000

rating table example

**http**
http://waterdata.usgs.gov/nwisweb/get_ratings?site_no=13052200&file_type=corr

**https**

https://staging.waterdata.usgs.gov/nwisweb/get_ratings?site_no=13052200&file_type=corr

**Comment by tjrocha** [comment]
Manual UI addition and compile tests passed. TODO: search for `https://staging.waterservices.usgs` and replace it with `https://waterservices.usgs` in the code on Jan 1, 2017.

**Comment by ktarbet** [comment]
USGS released this today: 
https://help.waterdata.usgs.gov/news/December%205%2C%202016

**Comment by tjrocha** [comment]
I've been running the non-staging https URLs on HDB with success. Should we migrate to the new https URL now?

**Comment by ktarbet** [comment]
Yes, please if there is a 'permanent' usgs url to use.

**Comment by tjrocha** [comment]
9f7af12

**Comment by ktarbet** [comment]
Thanks @tjrocha    I appreciate that fix!
