### ISSUE TITLE
Right Click Calculate - System.IndexOutOrRangeException

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#88]
To duplicate:
Create a empty database.
Right click on the folder 'Untitled' select "Calculate..."

Result:
Exception is thrown.

Expected Result:
Nothing 'bad' should  happen.

**Comment by tjrocha** [comment]
I was already in this area of the code and made the change in 52ea08989f300b2f278d753fa28a61c5c3ebd4d3. Tested locally and it works. Try it again and you should get the message box below. This will be returned if the folder is empty or does not contain at least 1 CalculationSeries().

![image](https://cloud.githubusercontent.com/assets/8174126/19862972/a9f57492-9f4f-11e6-9398-e9c8ca6fbcc7.png)

**Comment by ktarbet** [comment]
Thanks that fixes it.

**Comment by blounsbury** [comment]
Always multiple solutions to an issue. It seems to me that the bug is within PiscesForm.Enabling(). The Calculate menu should have been disabled in this case.
