### ISSUE TITLE
Add "&&" functionality to the tree filter text box

### ISSUE THREAD

**Issue by jcuhaciyan** [usbr/Pisces#91]
This would allow multiple search strings similar to the existing feature that allows a comma between search terms to get OR functionality.
![filter_box](https://cloud.githubusercontent.com/assets/4818531/20151195/7ce812f6-a676-11e6-97c0-494e5e2a1995.jpg)

The && would represent AND functionality in a search.  One use of this is scenarios -- where you wish to filter by other details.

**Comment by tjrocha** [comment]
Commit e374c84 adds this functionality as shown by the screenshots below

OR filter
![picture1](https://cloud.githubusercontent.com/assets/8174126/21534239/0ba5d532-cd19-11e6-9582-0ea56dbbc6ca.png)

AND filter
![picture2](https://cloud.githubusercontent.com/assets/8174126/21534240/0e6234d2-cd19-11e6-86b5-4c1c88591c66.png)

**Comment by tjrocha** [comment]
@jcuhaciyan - feel free to close this issue if you feel this solution works for your needs.

**Comment by blounsbury** [comment]
If you really want to get ambitious maybe add support for and/or combinations. Something like 'cle,gh&needed' would currently give an empty tree. But that is also a difficult problem.

**Comment by tjrocha** [comment]
Hmmm. That would be an interesting to code. We would have to do some kind of grouping enclosure so we know which string to group together since it is ambiguous given *cle,gh&needed* whether we want *(cle,gh)&needed* or *cle,(gh&needed)*... I'll look into this.
