### ISSUE TITLE
Add ImportIDWR feature (Daily data)

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#92]
Similar to USGS or Hydromet import dialogs.

Allow multiple stations separated by commas (like usgs).
Low level code (inherited from Series) already exists [here](https://github.com/usbr/Pisces/blob/master/TimeSeries/Idwr/IDWRDailySeries.cs)

http://www.waterdistrict1.com/   (Historical data retrieval )

Data to be used for flood control benefits analysis.  Also, data can be used for Upper Snake model input to separate reach gain data from diversions.  We will be able to calculate the reach gains directly in Pisces instead of relying on IDWR.

**Comment by tjrocha** [comment]
I've built several projects that process API requests and responses using the NuGet packages for Newtonsoft.Json and RestSharp. Would it be OK if I added these dependencies in working on this enhancement?

**Comment by tjrocha** [comment]
We can develop a dedicated interface that calls each API in sequence using the [service](https://research.idwr.idaho.gov/apps/Shared/WaterServices/).

1. Let user pick a River basin
https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/SitesByRiver?river=BOI

2. Select SiteID to get Site Info and available params https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/SiteDetails?sitelist=13190000

3. Let user pick date range and desired params
https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/HistoryAvailableYearsBySiteId?siteid=13190000&yeartype=CY&f=json

4. Get data
https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/history?siteid=13190000&yearlist=2017&yeartype=CY&f=json

**Comment by ktarbet** [comment]
Most important is solving issue #112 -- That is used by the application HydrometTools to update data data in the hydromet database.   I'll  eventually put HydrometTools code in the Applications directory.

**Comment by tjrocha** [comment]
Ok. I'll work on this today then. Thanks!

**Comment by tjrocha** [comment]
Working UI that dynamically hits the IDWR API and populates drop-downs is in a136f231ed6c8230babc24d31aacae1fae20c56d. Additional work to convert the JSON TS data to a Pisces Series() and add to Pisces tree in progress.

![image](https://cloud.githubusercontent.com/assets/8174126/25965482/fa6b6e02-363c-11e7-8040-62fdc0eacdfc.png)

![image](https://cloud.githubusercontent.com/assets/8174126/25965485/fda1bfe0-363c-11e7-9569-37aaa768ad5c.png)

![image](https://cloud.githubusercontent.com/assets/8174126/25965489/0096c1b4-363d-11e7-807f-6783dff9bd8c.png)

**Comment by ktarbet** [comment]
thanks @tjrocha -- That looks great!

**Comment by tjrocha** [comment]
Working Beta on 6e314d0db36ac013c7674c7b237553803b980b66. Test it out and let me know if you have any suggestions.

**Comment by ktarbet** [comment]
Thanks for working on this!  I'm having some trouble.

Steps to reproduce my test:
File -New (test.pdb)
Data-Add->IDWR
Select system ('Billingsley Creek')
Select River Site ('Idaho power ditch')
Start date  1/1/2017
end date 5/14/2017

![image](https://cloud.githubusercontent.com/assets/4818531/26063535/839f39ea-394b-11e7-959a-0b948a1fe37f.png)


![image](https://cloud.githubusercontent.com/assets/4818531/26063412/39742498-394b-11e7-9aa2-767c5b2e51aa.png)

**Comment by tjrocha** [comment]
Issue addressed by commit c08c6f83373f1d25e10c6e8a47f0012d4303e928. UI now checks selected Date Range and checks whether there is data from IDWR given the available years. IdwrSeries() also puts in missing data for the selected Date Range if no data exists.

![image](https://cloud.githubusercontent.com/assets/8174126/26075799/70000976-396b-11e7-9550-4db0352b8559.png)

**Comment by tjrocha** [comment]
@ktarbet: I saw that you merged my PR. Should I close this issue along with #112?
