### ISSUE TITLE
Calculate Dialog needs to support Hour and minute

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#99]
Issue:  Calculate uses the Dates selected (for yyyy-mm-dd), but system clock for hour and minute.

At a minimum the time should default to midnight when calculating 15 minute data.

![calcmenu](https://cloud.githubusercontent.com/assets/4818531/20577402/55efcc5c-b17f-11e6-8448-d184727b977e.png)

**Comment by blounsbury** [comment]
Is there a test case or example database to evaluate or test this?

**Comment by ktarbet** [comment]
Test file: [issue99.zip](https://github.com/usbr/Pisces/files/617383/issue99.zip)

To reproduce a problem:
Right click Calculate on the series 'ts' -- use date range  1/1/2016 to 1/1/2016
If you system clock is beyond 12:45 PM you will not get results.

Expected result is an daily average of 0.5 -- You can get this by computing full period of record.

**Comment by blounsbury** [comment]
I'm unable to reproduce the issue in the latest version 2.0.34 or from master.

**Comment by blounsbury** [comment]
I tried yesterday afternoon as well and it was working.
